<?php

namespace AppBundle\Repository;

/**
 * CollectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectRepository extends \Doctrine\ORM\EntityRepository
{
}
